"""Revision of nullable fields/Spotify_id for song

Revision ID: a283be5badc2
Revises: e9f3b4345181
Create Date: 2018-02-21 19:46:35.323702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a283be5badc2'
down_revision = 'e9f3b4345181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('albums', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('albums', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('artists', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('plays', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('plays', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('songs', sa.Column('spotify_id', sa.String(length=128), nullable=False))
    op.alter_column('songs', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('songs', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('songs', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('songs', 'spotify_id')
    op.alter_column('plays', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plays', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artists', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('albums', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('albums', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
